### ISSUE TITLE
Let user to fix failing check if possible

### ISSUE THREAD

**Issue by lzap** [iNecas/foreman_maintain#25]
We should not only check for state, but if it's possible and implemented, we should allow users to  fix the inconsistencies or errors interactively. This should be opt-in feature.

**Comment by iNecas** [comment]
Yes, this is one of the objectives we have from the day one. The way we define it still evolves (see next steps in https://github.com/iNecas/foreman_maintain/blob/276f9729f7426acad2455eef5ea7d8c382a7c645/README.md#checks vs https://github.com/iNecas/foreman_maintain/tree/checks-usability#checks, that is being proposed in https://github.com/iNecas/foreman_maintain/pull/29, but since we already aim for handling this, I'm closing this issue and done. Any additional feedback/requests from improvements once we have some real checks using this functionality are welcome
